name: Build

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Run app lint
        working-directory: ./app
        run: npm run lint
      - name: Run server lint
        working-directory: ./server
        run: npm run lint
      - name: Run server tests
        working-directory: ./server
        run: npm run test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
