name: Continuous Integration
on: push
  branches:
    - master

jobs:
  build:
    steps:
      - uses: actions/checkout@master
      - name: npm install, build, and test
        run: npm install
          npm run eslint
          npm run test
        env:
          CI: true
